<?php
/**
 * @file pinterest_verify.module
 *
 */

define('PINTEREST_VERIFY_META', 1);
define('PINTEREST_VERIFY_PAGE', 2);

/**
 * Implements hook_menu().
 */
function pinterest_verify_menu() {
  $items['admin/config/services/pinterest_site_verify'] = array(
    'title' => t('Pinterest Verify Website'),
    'description' => t('Add a pinterest verification tag or page to your Drupal site.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pinterest_verify_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pinterest_verify.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_init().
 */
function pinterest_verify_init() {
  $verify_method = variable_get('pinterest_verify_method', PINTEREST_VERIFY_META);
  $verify_meta = variable_get('pinterest_verify_meta', '');

  if ($verify_method == PINTEREST_VERIFY_META && !empty($verify_meta)) {
    $header = array(
      '#type' => 'html_tag',
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'p:domain_verify',
        'content' =>  $verify_meta,
      )
    );
    drupal_add_html_head($header, 'pinterest_verify');
  }
}

/**
 * Implements hook_menu_alter().
 */
function pinterest_verify_menu_alter(&$items) {
  $verify_method = variable_get('pinterest_verify_method', PINTEREST_VERIFY_PAGE);
  $verify_url = variable_get('pinterest_verify_page_url', '');

  if ($verify_method == PINTEREST_VERIFY_META && !empty($verify_url)) {
    $items[$verify_url] = array(
      'page callback' => '_pinterest_verify_page',
      'type' => MENU_CALLBACK,
    );
  }
}

function _pinterest_verify_page() {
  die(variable_get('pinterest_verify_page_content', ''));
}
